# --- MONITORES ---
monitor=,preferred,auto,1

# --- VARIABLES DE PROGRAMAS ---
$terminal = kitty
$fileManager = ranger --show drun
$menu = rofi --show drun
$browser = firefox

# --- INICIO AUTOMÁTICO ---
exec-once = waybar
exec-once = awww-daemon && awww img /home/wmasi_404/Downloads/bosque-montanas-ilustracion-digital_3840x2160_xtrafondos.com.jpg

#como pueden abrirse las ventanas
ayerrule = blur on, match:namespace wlogout

# --- ENTRADA (TECLADO LATAM) ---
input {
    kb_layout = latam
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = false
    }

    sensitivity = 0 
}

# --- ESTÉTICA GENERAL ---
general {
    gaps_in = 5
    gaps_out = 5
    border_size = 1
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    layout = dwindle
}

# --- DECORACIÓN (CORREGIDO) ---
decoration {
    rounding = 10

    blur {
        enabled = true
        size = 3
        passes = 1
    }

    #--- para las ventanas de waybar
  #  windowrulev2 = float,class:(nmtui),title:(nmtui)
#Bloque de sombras corregido y desactivado por tus problemas de hardware
    shadow {
        enabled = false
    }
}

# --- ANIMACIONES ---
animations {
    enabled = true
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

# --- DISEÑOS (LAYOUTS) ---
dwindle {
    pseudotile = true 
    preserve_split = true 
}


#Aqui supuestamente para controlar el audio no se
# Subir volumen (5% cada vez)
binde = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+

# Bajar volumen (5% cada vez)
binde = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-

# Silenciar/Quitar silencio (Mute)
bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

# Silenciar micrófono (opcional)
bind  = , XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

# --- ATAJOS DE TECLADO (BINDS) ---
$mainMod = SUPER

bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive, 
bind = $mainMod, M, exit, 
bind = $mainMod, E, exec, kitty -e ranger
bind = $mainMod, V, togglefloating, 
bind = $mainMod, R, exec, $menu
bind = $mainMod, P, pseudo,
bind = $mainMod, J, togglesplit, 
bind = $mainMod, F, exec, $browser
bind = $mainMode, T, exec, code
# Abrir Spotify con Fn + F9 (o solo F9 según tu BIOS)
bind = , F9, exec, spotify

# Mover foco
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Cambiar de Workspace
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6

# Mover ventana a Workspace
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6

# Mover/Redimensionar con mouse
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
